# Generated by Django 5.1.1 on 2024-10-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('MiddleName', models.CharField(max_length=30)),
                ('LasttName', models.CharField(max_length=30)),
                ('Suffix', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user email')),
                ('phone', models.CharField(max_length=15)),
                ('RedressNumber', models.CharField(max_length=30)),
                ('knownTravelerNumber', models.CharField(max_length=30)),
                ('emergencyFirstName', models.CharField(max_length=30)),
                ('emergencyLastName', models.CharField(max_length=30)),
                ('emergencyEmail', models.EmailField(max_length=254, unique=True, verbose_name='emergency email')),
                ('emergencyPhone', models.CharField(max_length=15)),
            ],
        ),
    ]
