# Generated by Django 5.1.1 on 2024-10-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_travelerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelerinfo',
            old_name='LasttName',
            new_name='LastName',
        ),
    ]
